name: "Feat Request"
description: "Suggest a new feature or enhancement"
title: "[FEAT] "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a clear and concise description of what the feature is."
      placeholder: "Write your description here..."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "Reason"
      description: "Why is this feature needed? What problem does it solve?"
      placeholder: "Write your reason here..."
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: "Possible Implementation"
      description: "Not required, but suggest an idea for implementing said feature."
      placeholder: "Write your suggestion here..."
    validations:
      required: false
  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: |
        List any specific requirements or conditions this feature must meet.
        You can write your own checklist using `- [ ] ` syntax.

        Example:
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] etc...
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
